config/routes.rb
Rails.application.routes.draw do

  root 'qualifications#index'
  get 'qualifications/:id' => 'qualifications#show', as: :qualifications

end

app/models/qualification.rb
class Qualification
  # TODO: make config
  URL = 'https://api.gojimo.net/api/v4/qualifications/'.freeze

  attr_reader :name, :id, :subjects

  def self.fetch_all
    JSON.parse(Faraday.get(URL).body).map do |qualification|
      new(qualification)
    end
  end

  def self.fetch(id:)
    new(JSON.parse(Faraday.get(URI.join(URL,id)).body))
  end

  def initialize(json)
    @id = json['id']
    @name = json['name']
    @subjects = json['subjects'].map{|subject_json| Subject.new(subject_json)}
  end
end

app/models/subject.rb
class Subject
  attr_reader :color, :name

  def initialize(json)
    @color = json['colour']
    @name = json['name']
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/qualifications_controller.rb
class QualificationsController < ApplicationController
  before_action :fetch_qualifications, only: :index
  before_action :fetch_qualification, only: :show

  def index
  end

  def show
  end

  private

  def fetch_qualifications
    @qualifications ||= Qualification.fetch_all
  end

  def fetch_qualification
    @qualification ||= Qualification.fetch(id: params.require(:id))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gojimo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/qualifications/index.html.erb
<h1> Qualifications: </h1>

<ul>
<% @qualifications.each do |qualification| %>
  <li>
    <%= link_to("#{qualification.name}", qualifications_path(id: qualification.id)) %>
  </li>
<% end %>
</ul>

app/views/qualifications/show.html.erb
<h1> Subjects for <%= @qualification.name %> </h1>
<ul>
<% @qualification.subjects.each do |subject| %>
  <li style="background-color:<%= subject.color %>">
    <%= subject.name %>
  </li>
<% end %>
</ul>